#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════
// proof-sync — miroir lisible des preuves d'auto-apprentissage des kybers.
//
//   node kybernos-sessions/proof-sync.mjs [--project <chemin>] [--home <DSH_HOME>]
//
// Écrit, par kyber, dans <project>/.kybers/<kyber>/ (sibling de l'endroit où
// vivaient les worktrees) :
//   • lessons.md  — leçons datées + runs + membres (données réelles du ledger) ;
//   • VERSION.md  — une ligne par commit local du dépôt des kybers touchant
//                   ce kyber (preuve versionnée ; vide et dit comme tel tant
//                   qu'aucun correctif n'y est passé).
// Aucune écriture ailleurs. Idempotent.
// ═══════════════════════════════════════════════════════════════════════════

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'
import { etatMemoire } from './index.js'

const arg = (nom, defaut) => {
  const i = process.argv.indexOf(nom)
  return i > 0 && process.argv[i + 1] ? process.argv[i + 1] : defaut
}
const home = arg('--home', process.env.DSH_HOME || join(homedir(), '.dsh'))
const projet = resolve(arg('--project', process.cwd()))
const kybersHome = join(home, 'kybers')

const git = (args) => {
  try { return execFileSync('git', args, { cwd: kybersHome, timeout: 4000 }).toString() } catch (e) { return '' }
}
const estGit = existsSync(join(kybersHome, '.git'))

const kybers = etatMemoire(kybersHome)
if (kybers.length === 0) {
  console.log('aucune mémoire de kyber trouvée dans ' + kybersHome)
  process.exit(0)
}

for (const k of kybers) {
  const dir = join(projet, '.kybers', k.id)
  mkdirSync(dir, { recursive: true })

  // lessons.md — lisible par un humain
  const membres = k.membres.map((m) => '| ' + m.role + ' | ' + m.runs + ' | ' + (m.outcome || '—') + ' | ' + String(m.dernier || '—').slice(0, 10) + ' |').join('\n')
  const lecons = k.lecons.map((l) => '- **' + String(l.ts || '').slice(0, 10) + '** — ' + l.texte + (l.tags.length > 0 ? ' `' + l.tags.join('`,`') + '`' : '')).join('\n')
  writeFileSync(join(dir, 'lessons.md'),
`# ${k.id} — lessons learned (mirror)

> Generated by \`proof-sync.mjs\` on ${new Date().toISOString().slice(0, 16).replace('T', ' ')} — source of truth: \`~/.dsh/kybers/${k.id}/memory/\`.
> Team members run together in a session; counts below are real ledger runs.

- **${k.totalLecons} lessons** · **${k.totalRuns} runs** · last: ${k.dernierOutcome || '—'}

| Member | Runs | Last outcome | Last run |
|---|---|---|---|
${membres}

## Lessons

${lecons}
`)

  // VERSION.md — une ligne par commit local touchant ce kyber
  let lignes = ''
  if (estGit) {
    const log = git(['log', '--oneline', '--date=short', '--pretty=format:%h %ad %s', '--', k.id])
    lignes = log.split('\n').filter((l) => l.trim() !== '').map((l) => '| ' + l.replace(' ', ' | ') + ' |').join('\n')
  }
  writeFileSync(join(dir, 'VERSION.md'),
`# ${k.id} — versions

${estGit ? '' : '> The kybers folder is not a git repository yet — no versions to show.\n'}
| Commit | Date | Change |
|---|---|---|
${lignes || '| — | — | no version has touched this kyber since the initial commit |'}
`)
  console.log('✓ ' + k.id + ' → ' + join('.kybers', k.id))
}
console.log('miroir écrit dans ' + join(projet, '.kybers'))
